### ISSUE TITLE
Add ability to add a name to combos

### ISSUE THREAD

**Issue by zethussuen** [ConnorBryan/smashcombos#42]
Combos in smash typically have shorthand names as they become more popular i.e. Luigi 0-death, or Fox's fair-footstool from sm4sh.

**Comment by ConnorBryan** [comment]
I thought about this. The reason I'm hesitant is because it's not as if it's a standard for all combos to be named, and coming up with names isn't easy. I feel like a lot would be corny. Maybe I'm wrong?

**Comment by zethussuen** [comment]
Was thinking that most combos wouldn't be named, but the more popular/commonly-used ones could have the option of having a name as an extra label.

**Comment by ConnorBryan** [comment]
Might that be a candidate for the `Notes` fields? `This combo is often known as <blah blah blah>`
