### ISSUE TITLE
Add ability to sort character combos

### ISSUE THREAD

**Issue by zethussuen** [ConnorBryan/smashcombos#43]
Would be nice to have the ability to view/sort/filter combos on a character's page by:
- Initial move
- % range
- whether it's true, 50/50, tech chase, follow DI

**Comment by ConnorBryan** [comment]
Yeah, this is definitely coming. You'll be able to sort by every section in the combo, etc. It didn't seem pertinent before there was enough content for it to matter, but it's coming soon.
